### ISSUE TITLE
`Cannot invoke "String.isEmpty()" because "path" is null`

### ISSUE THREAD

**Issue by SettingDust** [RayTrace082/untamedwilds#232]
```
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "path" is null
	at untamedwilds.util.EntityUtils.buildTooltipData(EntityUtils.java:128) ~[untamedwilds-1.18.2-2.4.0.jar%23329!/:1.18.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at untamedwilds.item.MobBottledItem.m_7373_(MobBottledItem.java:42) ~[untamedwilds-1.18.2-2.4.0.jar%23329!/:1.18.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:644) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,pl:rei_plugin_compatibilities:B,xf:fml:forge:itemstack,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:braincell.mixins.json:client.ItemStackClientMixin,pl:mixin:APP:mixins.mlib.json:MixinItemStack,pl:mixin:APP:canary.mixins.json:item.ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:biomemakeover-common.mixins.json:enchantment.ItemStackMixin,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:APP:dawncraft.mixin.json:MixinItemStack,pl:mixin:A}

```

**Comment by Davoleo** [comment]
Can confirm this happens, I've also experienced another tooltip issue that breaks REI search, I reported it in #233 
_[if you could include that in dawncraft-fixes as well it would be awesome]_

**Comment by SettingDust** [comment]
> Can confirm this happens, I've also experienced another tooltip issue that breaks REI search, I reported it in #233 _[if you could include that in dawncraft-fixes as well it would be awesome]_

Fixed. Haven't published
