### ISSUE TITLE
Untamed Wilds crashing in multiplayer

### ISSUE THREAD

**Issue by pintaku** [RayTrace082/untamedwilds#251]
https://pastebin.com/gEGFqaZd

---

works fine in singleplayer! i have searched far and wide to try and fix this, downgrading does not fix, and there are no later versions. any help would be VERY appreciated, thank you!

**Comment by suiramdev** [comment]
Anybody have found a way to fix this? A friend is having a similar issue :
```[00:06:00] [Render thread/ERROR] [minecraft/BlockableEventLoop]: Error executing task on Client
 
java.lang.NullPointerException: Cannot invoke "untamedwilds.util.EntityDataHolder.getScale(int)" because the return value of "untamedwilds.entity.ComplexMob.getEntityData(net.minecraft.world.entity.EntityType)" is null
 
	at untamedwilds.entity.ComplexMob.getModelScale(ComplexMob.java:195) ~[untamedwilds-1.19.2-3.0.2.jar%23294!/:1.19.2] {re:classloading}
 
	at untamedwilds.entity.mammal.EntityBaleenWhale.getMultiparts(EntityBaleenWhale.java:260) ~[untamedwilds-1.19.2-3.0.2.jar%23294!/:1.19.2] {re:classloading}
 
	at untamedwilds.entity.mammal.EntityBaleenWhale.<init>(EntityBaleenWhale.java:53) ~[untamedwilds-1.19.2-3.0.2.jar%23294!/:1.19.2] {re:classloading}
 ```

**Comment by Caltinor** [comment]
For context in the issue mentioned above.  Project MMO will use `EntityType.create` to create a default entity instance for getting entity stats and other information necessary to calculate the XP PMMO will award from it.

**Comment by Proxwian** [comment]
Same issue here, WITHOUT ProjectMMO

**Comment by Proxwian** [comment]
[crash-2023-08-22_23.25.35-client.txt](https://github.com/RayTrace082/untamedwilds/files/12411252/crash-2023-08-22_23.25.35-client.txt)

**Comment by RayTrace082** [comment]
Tested on 1.18.2, with ProjectMMO as a way to test default entity instances, and the only problems I can see are small visual issues (tested on both server and client)

Unless anyone can provide a setup with which I can replicate this crash, I will close the issue

**Comment by Proxwian** [comment]
You can test it on OxFORTPACK modpack version 8.2. Looks like I removing untamedwilds in another update

**Comment by Proxwian** [comment]
It happens in singleplayer too

**Comment by RayTrace082** [comment]
I have been exploring a bit on the OxFORTPACK pack with no issues, do you happen to have a world file where I can replicate the problem to check if my changes have fixed it?

**Comment by Caltinor** [comment]
> Tested on 1.18.2, with ProjectMMO as a way to test default entity instances, and the only problems I can see are small visual issues (tested on both server and client)
> 
> Unless anyone can provide a setup with which I can replicate this crash, I will close the issue

To test With pmmo: 
1. Enter any world
2. press "P" to open the glossary
3. click "Open Glossary" for the select menu. 
4. Choose "XP sources" for the first option and "entities" for the second. 
5. click "view info". 
6. See crash.

**Comment by RayTrace082** [comment]
Okay, I don't get any crash by following these instructions, gonna publish the 1.18 update in a bit and see if that fixes it

The only issue I do see is that mobs' heads look strange

**Comment by Caltinor** [comment]
So, I also created a sandboxed environment to test this and could not repeat the results.  Based on the modpacks i know have been experiencing the issue, my hypothesis at this point is that there is some sort of mixin and/or performance mod causing conflicts.  I had a similar rendering error using the same procedures on the Strictly Medieval modpack but it threw the error for another mod. 

For PMMO 1.19.2 I have added a client toggle to disable entity rendering in GUIs which seems to have solved this issue symptomatically.

**Comment by vgrynch** [comment]
1.19.2, client-side logs spammed by the same exceptions. After playing a while, client-side crashed finally.

**Comment by RayTrace082** [comment]
Should be fixed in the latest 1.19.2 version, post log if it is not
