### ISSUE TITLE
 Game Crash from Rendering entity in world untamedwilds:tortoise 1.16.5-36.2.39 Forge & OptiFine_1.16.5_HD_U_G8

### ISSUE THREAD

**Issue by Khan8615** [RayTrace082/untamedwilds#262]
The title states Minecraft version & forge version & optifine version.

the beta version currently in use is untamedwilds-1.16.5-1.5.8.jar
( link to it is below )
https://www.curseforge.com/minecraft/mc-mods/untamedwilds/files/3877295

Here's the stack trace.

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 8/16/23 2:51 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at untamedwilds.util.EntityUtils.getSkinFromEntity(EntityUtils.java:384) ~[?:1.16.5-1.5.8] {re:classloading}
	at untamedwilds.entity.ComplexMob.getTexture(ComplexMob.java:295) ~[?:1.16.5-1.5.8] {re:classloading}
	at untamedwilds.client.render.RendererTortoise.getEntityTexture(RendererTortoise.java:30) ~[?:1.16.5-1.5.8] {re:classloading}
	at untamedwilds.client.render.RendererTortoise.func_110775_a(RendererTortoise.java:13) ~[?:1.16.5-1.5.8] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_230496_a_(LivingRenderer.java:226) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cavesandcliffs.mixins.json:client.LivingEntityRendererMixin,pl:mixin:APP:twoplayersonehorse.mixins.json:LivingRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:178) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cavesandcliffs.mixins.json:client.LivingEntityRendererMixin,pl:mixin:APP:twoplayersonehorse.mixins.json:LivingRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(MobRenderer.java:47) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(MobRenderer.java:20) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:311) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixin.imdlib-betteranimalsplus.json:EntityRenderDispatcherAccessor,pl:mixin:APP:byg.mixins.json:client.MixinEntityRendererManager,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:2120) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.WorldRendererMixin,pl:mixin:APP:cavesandcliffs.mixins.json:client.WorldRendererMixin,pl:mixin:APP:mixins.cofhcore.json:WorldRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1742) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.WorldRendererMixin,pl:mixin:APP:cavesandcliffs.mixins.json:client.WorldRendererMixin,pl:mixin:APP:mixins.cofhcore.json:WorldRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mermod.mixins.json:GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mermod.mixins.json:GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$505/1658534033.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at untamedwilds.util.EntityUtils.getSkinFromEntity(EntityUtils.java:384) ~[?:1.16.5-1.5.8] {re:classloading}
	at untamedwilds.entity.ComplexMob.getTexture(ComplexMob.java:295) ~[?:1.16.5-1.5.8] {re:classloading}
	at untamedwilds.client.render.RendererTortoise.getEntityTexture(RendererTortoise.java:30) ~[?:1.16.5-1.5.8] {re:classloading}
	at untamedwilds.client.render.RendererTortoise.func_110775_a(RendererTortoise.java:13) ~[?:1.16.5-1.5.8] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_230496_a_(LivingRenderer.java:226) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cavesandcliffs.mixins.json:client.LivingEntityRendererMixin,pl:mixin:APP:twoplayersonehorse.mixins.json:LivingRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:178) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cavesandcliffs.mixins.json:client.LivingEntityRendererMixin,pl:mixin:APP:twoplayersonehorse.mixins.json:LivingRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(MobRenderer.java:47) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(MobRenderer.java:20) ~[?:?] {re:classloading,xf:OptiFine:default}
-- Entity being rendered --
Details:
	Entity Type: untamedwilds:tortoise (untamedwilds.entity.reptile.EntityTortoise)
	Entity ID: 8028
	Entity Name: Tortoise
	Entity's Exact location: -3827.70, 75.00, -500.63
	Entity's Block location: World: (-3828,75,-501), Chunk: (at 12,4,11 in -240,-32; contains blocks -3840,0,-512 to -3825,255,-497), Region: (-8,-1; contains chunks -256,-32 to -225,-1, blocks -4096,0,-512 to -3585,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: untamedwilds.client.render.RendererTortoise@42fd774
	Location: 4.93,-4.00,0.23 - World: (4,-4,0), Chunk: (at 4,-1,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 115.3125
	Delta: 0.2600752
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:311) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixin.imdlib-betteranimalsplus.json:EntityRenderDispatcherAccessor,pl:mixin:APP:byg.mixins.json:client.MixinEntityRendererManager,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:2120) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.WorldRendererMixin,pl:mixin:APP:cavesandcliffs.mixins.json:client.WorldRendererMixin,pl:mixin:APP:mixins.cofhcore.json:WorldRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1742) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.WorldRendererMixin,pl:mixin:APP:cavesandcliffs.mixins.json:client.WorldRendererMixin,pl:mixin:APP:mixins.cofhcore.json:WorldRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mermod.mixins.json:GameRendererMixin,pl:mixin:A}

-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['bmwchickk'/10021, l='ClientLevel', x=-3832.63, y=79.00, z=-500.85], RemoteClientPlayerEntity['Caithuwu'/371, l='ClientLevel', x=-3833.92, y=75.00, z=-508.16]]
	Chunk stats: Client Chunk Cache: 729, 287
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1 game time, 1 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$505/1658534033.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}

**Comment by Khan8615** [comment]
Apparently, according to my friend, they had put 5 turtles in their house & logged off, & then, when they went to reconnect to the server, this crashing began for them. I had to go to their home and kill their turtles so they could re-log back on the server lol.

**Comment by RayTrace082** [comment]
Sorry, but I am not going to fix this one

Not supporting 1.16.5 any longer, and since this looks like OptiFine is doing OptiFine things in the background, I'm not going to touch this
