### ISSUE TITLE
Log Spam 1.19.2

### ISSUE THREAD

**Issue by lSherozl** [RayTrace082/untamedwilds#298]
[15:07:42] [Worker-Main-8/ERROR]: Detected setBlock in a far chunk [621, 623], pos: MutableBlockPos{x=9948, y=63, z=9983}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:42] [Worker-Main-36/ERROR]: Detected setBlock in a far chunk [624, 626], pos: MutableBlockPos{x=9989, y=63, z=10028}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:42] [Worker-Main-36/ERROR]: Detected setBlock in a far chunk [624, 626], pos: MutableBlockPos{x=9987, y=63, z=10025}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:42] [Worker-Main-36/ERROR]: Detected setBlock in a far chunk [624, 626], pos: MutableBlockPos{x=9988, y=63, z=10025}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:42] [Worker-Main-36/ERROR]: Detected setBlock in a far chunk [624, 626], pos: MutableBlockPos{x=9990, y=63, z=10027}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:42] [Worker-Main-34/ERROR]: Detected setBlock in a far chunk [625, 620], pos: MutableBlockPos{x=10002, y=63, z=9931}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:42] [Worker-Main-34/ERROR]: Detected setBlock in a far chunk [624, 620], pos: MutableBlockPos{x=9997, y=63, z=9926}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:42] [Worker-Main-34/ERROR]: Detected setBlock in a far chunk [624, 620], pos: MutableBlockPos{x=9998, y=63, z=9924}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:42] [Worker-Main-34/ERROR]: Detected setBlock in a far chunk [624, 620], pos: MutableBlockPos{x=9997, y=63, z=9926}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:42] [Worker-Main-34/ERROR]: Detected setBlock in a far chunk [624, 620], pos: MutableBlockPos{x=9999, y=63, z=9928}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:42] [Worker-Main-34/ERROR]: Detected setBlock in a far chunk [624, 620], pos: MutableBlockPos{x=9997, y=63, z=9931}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:42] [Worker-Main-34/ERROR]: Detected setBlock in a far chunk [624, 621], pos: MutableBlockPos{x=9999, y=63, z=9938}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:43] [Worker-Main-56/ERROR]: Detected setBlock in a far chunk [626, 622], pos: MutableBlockPos{x=10020, y=63, z=9958}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:44] [Worker-Main-22/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10063, y=63, z=10004}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:44] [Worker-Main-22/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10061, y=63, z=10007}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:44] [Worker-Main-22/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10059, y=63, z=10008}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:44] [Worker-Main-22/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10055, y=63, z=10005}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:44] [Worker-Main-22/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10061, y=63, z=10005}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:44] [Worker-Main-22/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10055, y=63, z=10006}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:44] [Worker-Main-22/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10051, y=63, z=10005}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:44] [Worker-Main-22/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10049, y=63, z=10004}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:44] [Worker-Main-22/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10060, y=63, z=10006}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:44] [Worker-Main-22/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10059, y=63, z=10006}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}
[15:07:44] [Worker-Main-22/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10054, y=63, z=10009}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@335a0cc3: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@52fc3a6a}

**Comment by lSherozl** [comment]
More log spam that MAY or MAY NOT be involved in chunk loading issues 0:46:15] [Worker-Main-26/ERROR]: Detected setBlock in a far chunk [627, 625], pos: MutableBlockPos{x=10037, y=63, z=10002}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:16] [Worker-Main-19/ERROR]: Detected setBlock in a far chunk [622, 621], pos: MutableBlockPos{x=9967, y=63, z=9939}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:16] [Worker-Main-19/ERROR]: Detected setBlock in a far chunk [622, 621], pos: MutableBlockPos{x=9961, y=63, z=9942}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:20] [Worker-Main-26/ERROR]: Detected setBlock in a far chunk [628, 626], pos: MutableBlockPos{x=10061, y=63, z=10025}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:20] [Worker-Main-26/ERROR]: Detected setBlock in a far chunk [628, 626], pos: MutableBlockPos{x=10063, y=63, z=10024}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:20] [Worker-Main-26/ERROR]: Detected setBlock in a far chunk [628, 626], pos: MutableBlockPos{x=10061, y=63, z=10020}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:20] [Worker-Main-26/ERROR]: Detected setBlock in a far chunk [628, 626], pos: MutableBlockPos{x=10058, y=63, z=10019}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:20] [Worker-Main-26/ERROR]: Detected setBlock in a far chunk [628, 626], pos: MutableBlockPos{x=10058, y=63, z=10020}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:20] [Worker-Main-26/ERROR]: Detected setBlock in a far chunk [629, 626], pos: MutableBlockPos{x=10064, y=63, z=10019}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:20] [Worker-Main-26/ERROR]: Detected setBlock in a far chunk [628, 626], pos: MutableBlockPos{x=10055, y=63, z=10030}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:20] [Worker-Main-26/ERROR]: Detected setBlock in a far chunk [628, 626], pos: MutableBlockPos{x=10052, y=63, z=10025}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:20] [Worker-Main-26/ERROR]: Detected setBlock in a far chunk [628, 626], pos: MutableBlockPos{x=10051, y=63, z=10025}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:20] [Worker-Main-26/ERROR]: Detected setBlock in a far chunk [628, 626], pos: MutableBlockPos{x=10051, y=63, z=10029}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:20] [Worker-Main-26/ERROR]: Detected setBlock in a far chunk [628, 626], pos: MutableBlockPos{x=10050, y=63, z=10025}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:21] [Render thread/INFO]: Loaded 1034 advancements
[20:46:22] [Worker-Main-31/ERROR]: Detected setBlock in a far chunk [629, 624], pos: MutableBlockPos{x=10068, y=63, z=9998}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:22] [Worker-Main-31/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10063, y=63, z=10005}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:22] [Worker-Main-31/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10061, y=63, z=10006}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:22] [Worker-Main-31/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10057, y=63, z=10003}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:22] [Worker-Main-31/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10063, y=63, z=10003}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:22] [Worker-Main-31/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10057, y=63, z=10004}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:22] [Worker-Main-31/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10053, y=63, z=10003}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:22] [Worker-Main-31/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10051, y=63, z=10002}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:22] [Worker-Main-31/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10062, y=63, z=10004}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:22] [Worker-Main-31/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10061, y=63, z=10004}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:22] [Worker-Main-31/ERROR]: Detected setBlock in a far chunk [628, 625], pos: MutableBlockPos{x=10056, y=63, z=10007}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:22] [Worker-Main-39/ERROR]: Detected setBlock in a far chunk [624, 619], pos: MutableBlockPos{x=9990, y=63, z=9904}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:22] [Worker-Main-39/ERROR]: Detected setBlock in a far chunk [624, 619], pos: MutableBlockPos{x=9987, y=63, z=9904}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:22] [Worker-Main-39/ERROR]: Detected setBlock in a far chunk [624, 619], pos: MutableBlockPos{x=9989, y=63, z=9907}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:22] [Worker-Main-39/ERROR]: Detected setBlock in a far chunk [623, 619], pos: MutableBlockPos{x=9983, y=63, z=9915}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:23] [Worker-Main-10/ERROR]: Detected setBlock in a far chunk [629, 627], pos: MutableBlockPos{x=10072, y=63, z=10033}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:23] [Worker-Main-10/ERROR]: Detected setBlock in a far chunk [629, 627], pos: MutableBlockPos{x=10069, y=63, z=10032}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:23] [Worker-Main-10/ERROR]: Detected setBlock in a far chunk [629, 626], pos: MutableBlockPos{x=10071, y=63, z=10028}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:23] [Worker-Main-10/ERROR]: Detected setBlock in a far chunk [629, 627], pos: MutableBlockPos{x=10075, y=63, z=10033}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:23] [Worker-Main-10/ERROR]: Detected setBlock in a far chunk [629, 627], pos: MutableBlockPos{x=10073, y=63, z=10032}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:23] [Worker-Main-10/ERROR]: Detected setBlock in a far chunk [629, 626], pos: MutableBlockPos{x=10072, y=63, z=10029}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:24] [Worker-Main-49/ERROR]: Hanging entity at invalid position: BlockPos{x=124, y=-23, z=87}
[20:46:25] [Worker-Main-19/ERROR]: Hanging entity at invalid position: BlockPos{x=114, y=-23, z=87}
[20:46:25] [Worker-Main-19/ERROR]: Hanging entity at invalid position: BlockPos{x=114, y=-23, z=87}
[20:46:25] [Worker-Main-32/ERROR]: Detected setBlock in a far chunk [626, 630], pos: MutableBlockPos{x=10029, y=63, z=10080}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:25] [Worker-Main-25/ERROR]: Hanging entity at invalid position: BlockPos{x=114, y=-23, z=87}
[20:46:25] [Worker-Main-36/ERROR]: Hanging entity at invalid position: BlockPos{x=124, y=-23, z=87}
[20:46:25] [Worker-Main-12/ERROR]: Hanging entity at invalid position: BlockPos{x=114, y=-23, z=87}
[20:46:25] [Worker-Main-12/ERROR]: Detected setBlock in a far chunk [629, 625], pos: MutableBlockPos{x=10077, y=63, z=10006}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:46:25] [Worker-Main-12/ERROR]: Detected setBlock in a far chunk [629, 625], pos: MutableBlockPos{x=10076, y=63, z=10006}, status: minecraft:features, currently generating: Placed Direct{Configured: untamedwilds.world.gen.feature.FeatureFloatingPlants@5b503148: net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration@1a9f86ba}
[20:47:05] [ModernFix integrated server watchdog/ERROR]: A single server tick has taken 40001, more than 40000 milliseconds
[20:47:07] [ModernFix integrated server watchdog/ERROR]: Thread Dump:
"Render thread" prio=10 Id=1 RUNNABLE
	at java.base@17.0.3/java.lang.Object.hashCode(Native Method)
	at java.base@17.0.3/java.util.HashMap.hash(HashMap.java:338)
	at java.base@17.0.3/java.util.HashMap.getNode(HashMap.java:568)
	at java.base@17.0.3/java.util.HashMap.get(HashMap.java:556)
	at TRANSFORMER/flywheel@0.6.10-20/com.jozufozu.flywheel.util.WorldAttached.get(WorldAttached.java:46)
	at TRANSFORMER/create@0.5.1.f/com.simibubi.create.content.contraptions.render.ContraptionRenderDispatcher.beginFrame(ContraptionRenderDispatcher.java:74)
	at TRANSFORMER/create@0.5.1.f/com.simibubi.create.content.contraptions.render.__ContraptionRenderDispatcher_beginFrame_BeginFrameEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus$$Lambda$4978/0x0000000800f92730.invoke(Unknown Source)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.LevelRenderer.handler$ccd000$setupRender(LevelRenderer.java:26118)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.LevelRenderer.m_194338_(LevelRenderer.java)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.LevelRenderer.invokeSetupRender(LevelRenderer.java)
	at TRANSFORMER/oculus@1.6.9/net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:417)
	at TRANSFORMER/oculus@1.6.9/net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:1030)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.LevelRenderer.handler$bfk000$iris$renderTerrainShadows(LevelRenderer.java:9670)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1151)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.3/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.5/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.5/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler$$Lambda$907/0x00000008004d5238.run(Unknown Source)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at app/cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

"Reference Handler" daemon prio=10 Id=2 RUNNABLE
	at java.base@17.0.3/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
	at java.base@17.0.3/java.lang.ref.Reference.processPendingReferences(Reference.java:253)
	at java.base@17.0.3/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)

**Comment by twSparkleCat** [comment]
Same issue with
`Detected setBlock in a far chunk`
