### ISSUE TITLE
Spawning Untamed Wilds Mobs kicks player from server, "Packet Processing Error"

### ISSUE THREAD

**Issue by VampireSpaceCat** [RayTrace082/untamedwilds#44]
[07.08 18:57:31] [Server] [ERROR] Error whilst processing packet net.minecraft.network.play.client.CPlayerTryUseItemPacket@69cf6af7 for Cat_Cowboy[/24.51.191.203:61550]
[07.08 18:57:31] [Server] java.lang.NullPointerExceptionnull
[07.08 18:57:31] [Server] 	at untamedwilds.entity.ComplexMob.chooseSkinForSpecies(ComplexMob.java:109) ~[untamedwilds:1.16.5-1.3.1]
[07.08 18:57:31] [Server] 	at untamedwilds.util.EntityUtils.createMobFromItem(EntityUtils.java:134) ~[untamedwilds:1.16.5-1.3.1]
[07.08 18:57:31] [Server] 	at untamedwilds.item.MobBucketedItem.func_203792_a(MobBucketedItem.java:46) ~[untamedwilds:1.16.5-1.3.1]
[07.08 18:57:31] [Server] 	at net.minecraft.item.BucketItem.func_77659_a(BucketItem.java:94) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:253) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:353) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:1527) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(CPlayerTryUseItemPacket.java:30) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(CPlayerTryUseItemPacket.java:9) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$1(PacketThreadUtil.java:28) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:152) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:888) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:178) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:125) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:871) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:865) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:135) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:851) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771) ~[?:?]
[07.08 18:57:31] [Server] 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?]
[07.08 18:57:31] [Server] 	at java.lang.Thread.run(Thread.java:834) [?:?]
[07.08 18:57:31] [Disconnect] Cat_Cowboy has disconnected, reasonPacket processing error

**Comment by RayTrace082** [comment]
More information? Did you update versions in an existing world? Which mob caused this?
