### ISSUE TITLE
The egg item does not operate in a multi-server, but operates in a single.

### ISSUE THREAD

**Issue by agileahn2** [RayTrace082/untamedwilds#70]
**Describe the bug**
//The sentence may be strange because I am not good at English. I'm sorry.
Even if you hold the egg in your hand and click it right, it doesn't work. 
The number of items to know does not decrease. The baby mob is not even summoned. 
In the single world, egg items are consumed and baby mobs are summoned.

**Steps To Reproduce**
1. open forge server(1.16.5_36.2.8, I have used 36.2.0, 36.2.6, too)
2. Enter the server and use the eggs. (I used the eggs that tortoise laid.)
3. Check the error message on the cmd.

**Crash Log**
It's not a crash, it's just an error, so I'm attaching an error message here.
-----------------------------------------------------------------------------------------
[12:24:42] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.NullPointerException: null
        at untamedwilds.entity.ComplexMob.chooseSkinForSpecies(ComplexMob.java:118) ~[?:1.16.5-1.4.1] {re:classloading}
        at untamedwilds.item.MobEggItem.func_195939_a(MobEggItem.java:64) ~[?:1.16.5-1.4.1] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:644) ~[?:?] {re:classloading}
        at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:187) ~[?:?] {re:mixin,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:353) ~[?:?] {re:computing_frames,re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil$$Lambda$10653/1022987764.run(Unknown Source) ~[?:?] {}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer$$Lambda$9781/256517874.run(Unknown Source) [?:?] {}
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
--------------------------------------------------------------------------------------------------------------------------------------------

**Screenshots**
I'm not sure if I have a screenshot to show you.

**Version (please complete the following information):**
 - Minecraft version: [1.16.5]
 - Version of the mod: [1.4.1]
 - Additional mods: [
 - upgrade_aquatic-1.16.5-3.1.0
 - unnamedanimalmod-1.0.2
 - twilightforest-1.16.5-4.0.490-universal
 - savageandravage-1.16.5-3.1.0
 - Quark-r2.4-316
 - Patchouli-1.16.4-53.2
 - neapolitan-1.16.5-2.1.0
 - mowziesmobs-1.5.18
 - jei-1.16.5-7.7.0.106
 - Hwyla-forge-1.10.11-B78_1.16.2
 - FarmersDelight-1.16.5-0.4.6
 - extraboats-1.16.5-2.1.0
 - environmental-1.16.5-1.1.0
 - endergetic-1.16.4-3.0.0
 - citadel-1.8.1-1.16.5
 - buzzier_bees-1.16.5-3.0.1
 - berry_good-1.16.5-4.1.1
 - bamboo_blocks-1.16.5-3.0.0
 - autumnity-1.16.5-2.1.1
 - AutoRegLib-1.6-49
 - atmospheric-1.16.5-3.1.0
 - allurement-1.16.5-1.2.0
 - alexsmobs-1.12.1
 - abnormals_delight-1.16.5-1.2.0
 - abnormals_core-1.16.5-3.3.0]

**Comment by RayTrace082** [comment]
Thank you for being the very first person to provide a bug report on the subject of mob eggs not working, alongside the steps as to how to reproduce it
Will probably be a while until this is addressed, as I am a bit busy, but expect it to get fixed nonetheless

**Comment by GlowPon3** [comment]
Having the same issue.  Server is running forge 36.2.0 client is running forge 36.2.9 but everything else seems to work.  Until you get this fixed, is there a inclusive 'favorite food' list somewhere?

**Comment by RayTrace082** [comment]
Should be fixed on the latest version
