### ISSUE TITLE
"Untamed wilds encountered an error during the sided setup event phase" Error when opened minecraft in newest version (1.1.0)

### ISSUE THREAD

**Issue by TheEvilEye05** [RayTrace082/untamedwilds#8]
This is the crash report:

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 5/26/21 12:56 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$7387/2054574724.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$6279/162566028.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:rpgz.mixins.json:GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.23.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$488/1066949254.call(Unknown Source) [forge-1.16.5-36.1.23.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:1.8.0_51] {}
-- MOD untamedwilds --
Details:
	Mod File: untamedwilds-1.16.5-1.1.0.jar
	Failure message: Untamed Wilds (untamedwilds) encountered an error during the sided_setup event phase
		java.lang.NullPointerException: null
	Mod Version: 1.1.0
	Mod Issue URL: https://github.com/RayTrace082/untamedwilds/issues
	Exception message: java.lang.NullPointerException
Stacktrace:
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:1.8.0_51] {}
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.client.registry.RenderingRegistry.registerEntityRenderingHandler(RenderingRegistry.java:44) ~[?:?] {re:classloading}
	at untamedwilds.init.ModEntity.registerRendering(ModEntity.java:235) ~[?:1.16.5-1.1.0] {re:classloading}
	at untamedwilds.UntamedWilds.setupClient(UntamedWilds.java:70) ~[?:1.16.5-1.1.0] {re:classloading}
	at untamedwilds.UntamedWilds$$Lambda$4054/425598203.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2921/1819552644.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2551/438049370.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3155/2031209493.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4906077856 bytes (4678 MB) / 6408896512 bytes (6112 MB) up to 6408896512 bytes (6112 MB)
	CPUs: 4
	JVM Flags: 10 total; -Xmn128M -Xmx6102M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.23.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.23.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.23.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.23.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-OptiFine-1.16.5_HD_U_G8_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.23.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.23
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.23-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |ENQUEUE_IM|NOSIGNATURE
		FarmersDelight-1.16.5-0.4.2.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.4.2        |ENQUEUE_IM|NOSIGNATURE
		crafting-dead-virus-1.16.5-1.0.0-alpha.jar        |Crafting Dead Virus           |craftingdeadvirus             |1.0.0-alpha         |ENQUEUE_IM|NOSIGNATURE
		TreeChop-1.16.4-0.14.1.jar                        |HT's TreeChop                 |treechop                      |0.14.1              |ENQUEUE_IM|NOSIGNATURE
		rpgz-0.4.4-forge.jar                              |RpgZ                          |rpgz                          |0.4.4-forge         |ENQUEUE_IM|NOSIGNATURE
		NaturalProgression-1.16.5-1.4.0.jar               |Natural Progression           |natural-progression           |1.4.0               |ENQUEUE_IM|NOSIGNATURE
		ImmersiveEngineering-1.16.5-4.2.4-134.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-4.2.4-134    |ENQUEUE_IM|44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		locks-3.0.jar                                     |Locks                         |locks                         |3.0                 |ENQUEUE_IM|NOSIGNATURE
		crafting-dead-core-1.16.5-1.4.1-alpha.jar         |Crafting Dead                 |craftingdead                  |1.4.1-alpha         |ENQUEUE_IM|NOSIGNATURE
		jei-1.16.5-7.7.0.91.jar                           |Just Enough Items             |jei                           |7.7.0.91            |ENQUEUE_IM|NOSIGNATURE
		rsgauges-1.16.4-1.2.10.jar                        |Gauges and Switches           |rsgauges                      |1.2.10              |ENQUEUE_IM|bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		Patchouli-1.16.4-51.jar                           |Patchouli                     |patchouli                     |1.16.4-51           |ENQUEUE_IM|NOSIGNATURE
		journeymap-1.16.5-5.7.1.jar                       |Journeymap                    |journeymap                    |5.7.1               |ENQUEUE_IM|NOSIGNATURE
		polymorph-forge-1.16.5-0.24.jar                   |Polymorph                     |polymorph                     |1.16.5-0.24         |ENQUEUE_IM|NOSIGNATURE
		comforts-forge-1.16.4-4.0.1.0.jar                 |Comforts                      |comforts                      |1.16.4-4.0.1.0      |ENQUEUE_IM|NOSIGNATURE
		citadel-1.6.3.jar                                 |Citadel                       |citadel                       |1.6.3               |ENQUEUE_IM|NOSIGNATURE
		untamedwilds-1.16.5-1.1.0.jar                     |Untamed Wilds                 |untamedwilds                  |1.1.0               |ERROR     |NOSIGNATURE
		backpacked-1.10.0-1.16.3.jar                      |Backpacked                    |backpacked                    |1.10.0              |ENQUEUE_IM|NOSIGNATURE
		lostcities-1.16-4.0.8-beta.jar                    |LostCities                    |lostcities                    |1.16-4.0.8-beta     |ENQUEUE_IM|NOSIGNATURE
		BadMobs-1.16.5-9.0.3.jar                          |BadMobs                       |badmobs                       |9.0.3               |ENQUEUE_IM|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		buildersaddition-1.16.5-20210421a.jar             |Builders Crafts & Addition    |buildersaddition              |1.16.5-20210421a    |ENQUEUE_IM|NOSIGNATURE
		SpartanWeaponry-1.16.4-2.1.0-beta-4.jar           |Spartan Weaponry              |spartanweaponry               |2.1.0 beta 4        |ENQUEUE_IM|NOSIGNATURE
		engineersdecor-1.16.4-1.1.13.jar                  |Engineer's Decor              |engineersdecor                |1.1.13              |ENQUEUE_IM|bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		JEITweaker-1.16.5-1.0.1.15.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.15            |ENQUEUE_IM|NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.284.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.284           |ENQUEUE_IM|NOSIGNATURE
		ImmersivePetroleum-1.16.5-3.2.0-3.jar             |Immersive Petroleum           |immersivepetroleum            |3.2.0-3             |ENQUEUE_IM|NOSIGNATURE
		forge-1.16.5-36.1.23-universal.jar                |Forge                         |forge                         |36.1.23             |ENQUEUE_IM|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		moveplus-1.16.4-2.5.1.jar                         |Move Plus                     |moveplus                      |1.16.4-2.5.1        |ENQUEUE_IM|NOSIGNATURE
		tl_skin_cape_forge_1.16.5-1.19.jar                |TLSkinCape                    |tlskincape                    |1.19                |ENQUEUE_IM|19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		supplementaries-1.16.5-0.12.1.jar                 |Supplementaries               |supplementaries               |1.16.5-0.12.1       |ENQUEUE_IM|NOSIGNATURE
		too_hard_for_me-1.0.0.jar                         |Too Hard For Me               |too_hard_for_me               |1.0.0               |ENQUEUE_IM|NOSIGNATURE
		corpse-1.16.4-1.0.4.jar                           |Corpse                        |corpse                        |1.16.4-1.0.4        |ENQUEUE_IM|NOSIGNATURE
		chipped-1.0.5.jar                                 |Chipped                       |chipped                       |1.0.5               |ENQUEUE_IM|NOSIGNATURE
	Crash Report UUID: 28f1f7b2-bed4-458e-8f75-dac983664796
	Patchouli open book context: n/a
	OptiFine Version: OptiFine_1.16.5_HD_U_G8_pre2
	OptiFine Build: 20210305-002749
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4963
	OpenGlRenderer: Intel(R) HD Graphics 4400
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by RayTrace082** [comment]
I cannot replicate this crash. The usual suspect (Optifine) seems to work alright with Untamed Wilds

Could you share more information about how you triggered this crash? Was it while launching the game? When creating a world? When exploring the world?
Also, are you updating the mod on a pre-existing world?
